# Generated by Django 4.0.1 on 2022-01-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.CharField(default='default-a1', max_length=255)),
                ('a2', models.CharField(default='default-a2', max_length=255)),
                ('a3', models.CharField(default='default-a3', max_length=255)),
                ('a4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a2.modela')),
            ],
        ),
    ]
