# Generated by Django 4.0.1 on 2022-01-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0002_modelb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modela',
            old_name='a1',
            new_name='title_category',
        ),
    ]
